FROM alpine:latest

# https://mirrors.alpinelinux.org/
RUN sed -i 's@dl-cdn.alpinelinux.org@ftp.halifax.rwth-aachen.de@g' /etc/apk/repositories

RUN apk update
RUN apk upgrade

# required by qemu
RUN apk add --no-cache \
 make \
 samurai \
 perl \
 python3 python3-dev \
 gcc \
 libc-dev \
 pkgconf \
 linux-headers \
 zlib-dev zlib-static \
 zstd-dev zstd-static \
 pcre2-dev pcre2-static \
 flex swig bison py3-setuptools \
 libgcrypt-dev libgcrypt-static nettle-dev nettle-static libgpg-error-dev libgpg-error-static \
 lzo-dev passt gmp-dev gmp-static \
 bash xz git patch aria2 curl cmake jq \
 gettext gettext-dev autoconf automake libtool sqlite-dev sqlite-static lsb-release-minimal


# required to compile Slirp as static lib and qemu-system
RUN apk add --no-cache \
 bzip2-dev bzip2-static ncurses-static \
 libpng-dev libpng-static libjpeg-turbo-static libjpeg-turbo-dev \
 libxkbcommon-static libxkbcommon-dev \
 libx11-static zstd-static libunwind-dev libunwind-static libbsd-dev libbsd-static \
 git meson ninja-build gettext-static cyrus-sasl-static \
 build-base liburing-dev libaio-dev alpine-sdk \
 libsndfile-static libsndfile-dev openssl-libs-static \
 lz4-static lz4-dev pixman-static pixman-dev libudev-zero-dev libcap-static libcap-ng-static libcap-ng-dev \
 libxext-static libxext-dev
 
COPY build-static-lib-alpine.sh build-static-lib.sh
RUN chmod +x ./build-static-lib.sh
RUN bash ./build-static-lib.sh    


# additional

WORKDIR /work

COPY command/base command/base
COPY command/fetch command/fetch
RUN /work/command/fetch

COPY command/extract command/extract
RUN /work/command/extract

COPY patch patch
COPY command/patch command/patch
RUN /work/command/patch

COPY command/configure-alpine command/configure
RUN chmod +x /work/command/configure
RUN /work/command/configure

COPY command/make command/make
RUN /work/command/make

COPY command/install command/install
RUN /work/command/install

COPY command/package command/package
ENV XZ_OPT=-e9
RUN /work/command/package
