#!/bin/bash

set -e

. $(dirname $0)/base

WORKDIR "/work/out/${QEMU_SRC_BASENAME}"
RUN "/work/src/${QEMU_SRC_BASENAME}/configure" \
    --prefix="/work/dst/${QEMU_ARTIFACT_BASENAME}" \
    --disable-debug-info \
    --disable-werror \
    --enable-system \
    --enable-linux-user \
    --target-list=x86_64-softmmu,x86_64-linux-user,aarch64-softmmu,aarch64-linux-user \
    --enable-kvm \
    --enable-virtfs \
    --enable-qcow1 \
    --enable-vmdk \
    --enable-fuse \
    --extra-ldflags='-lgio-2.0 -leconf' \
    --enable-cap-ng \
    --enable-slirp --enable-gio --enable-passt --enable-nettle \
    --enable-rust --cc=clang --rust-target-triple=${HOST_ARCH}-chimera-linux-musl \
    --enable-libusb --enable-usb-redir --enable-vnc --enable-sdl --enable-sdl-image --enable-fdt --enable-linux-aio --enable-linux-io-uring --enable-pixman --enable-vvfat --enable-zstd --enable-bzip2 --enable-png --enable-vnc-jpeg -enable-slirp=system --enable-lto --static
